"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { cancelScheduledDeletion, deleteAccountImmediately, scheduleAccountDeletion, type DeletionActionResult } from "../../lib/admin/deletionActions";
import { DELETION_BASES, MIN_INTERNAL_REASON, MIN_PUBLIC_REASON, MAX_REASON, VIOLATION_CATEGORIES, type DeletionBasis, type ViolationCategory } from "../../lib/admin/restrictionTypes";

type Mode = "schedule" | "immediate" | "cancel";
export function DeletionControls({ userId, deletionPending, writesEnabled }: { userId: string; deletionPending: boolean; writesEnabled: boolean }) {
  const router = useRouter(); const inFlight = useRef(false);
  const [mode, setMode] = useState<Mode | null>(null); const [category, setCategory] = useState<ViolationCategory>("targeted_harassment");
  const [publicReason, setPublicReason] = useState(""); const [internalReason, setInternalReason] = useState("");
  const [basis, setBasis] = useState<DeletionBasis>("student_reports"); const [evidence, setEvidence] = useState(""); const [noEvidence, setNoEvidence] = useState(false); const [skipAppeal, setSkipAppeal] = useState(false); const [confirmation, setConfirmation] = useState(""); const [pending, setPending] = useState(false); const [result, setResult] = useState<DeletionActionResult | null>(null);
  const destructive = mode === "schedule" || mode === "immediate";
  const valid = mode === "cancel" ? internalReason.trim().length >= MIN_INTERNAL_REASON && confirmation.trim().toUpperCase() === "CANCEL DELETION" : destructive && publicReason.trim().length >= MIN_PUBLIC_REASON && publicReason.trim().length <= MAX_REASON && internalReason.trim().length >= MIN_INTERNAL_REASON && internalReason.trim().length <= MAX_REASON && (!!evidence.trim() || noEvidence) && (mode !== "immediate" || skipAppeal) && confirmation.trim().toUpperCase() === (mode === "immediate" ? "DELETE NOW" : "DELETE");
  async function submit() { if (!mode || !valid || inFlight.current) return; inFlight.current = true; setPending(true); setResult(null); try { const res = mode === "cancel" ? await cancelScheduledDeletion(userId, internalReason, confirmation) : mode === "immediate" ? await deleteAccountImmediately({ userId, violationCategory: category, publicReason, internalReason, basis, evidenceReferences: evidence, noEvidenceConfirmed: noEvidence, confirmation, immediate: true, skipAppealAcknowledged: skipAppeal }) : await scheduleAccountDeletion({ userId, violationCategory: category, publicReason, internalReason, basis, evidenceReferences: evidence, noEvidenceConfirmed: noEvidence, confirmation }); setResult(res); if (res.ok) router.refresh(); } finally { setPending(false); inFlight.current = false; } }
  function close() { if (!pending) { setMode(null); setResult(null); setConfirmation(""); } }
  return <div className="mt-4 border-t pt-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-500">Permanent deletion</p><div className="flex flex-wrap gap-2">{!deletionPending && <><button disabled={!writesEnabled} type="button" onClick={() => setMode("schedule")} className="rounded-lg bg-red-50 px-3 py-1.5 text-xs font-semibold text-red-700 disabled:opacity-50">Schedule permanent deletion</button><button disabled={!writesEnabled} type="button" onClick={() => setMode("immediate")} className="rounded-lg border border-red-300 px-3 py-1.5 text-xs font-semibold text-red-800 disabled:opacity-50">Delete immediately</button></>}{deletionPending && <button disabled={!writesEnabled} type="button" onClick={() => setMode("cancel")} className="rounded-lg bg-gray-100 px-3 py-1.5 text-xs font-semibold text-gray-800 disabled:opacity-50">Cancel scheduled deletion</button>}</div>
  {mode && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><h3 className="text-base font-semibold text-gray-900">{mode === "schedule" ? "Schedule permanent deletion" : mode === "immediate" ? "Delete immediately" : "Cancel scheduled deletion"}</h3>{destructive && <p className="mt-2 text-sm text-red-700">{mode === "immediate" ? "This emergency action skips the seven-day appeal period. The durable worker processes it after confirmation." : "Access is blocked immediately. Permanent deletion is scheduled exactly seven days later and may be appealed by email."}</p>}
  {destructive && <><label className="mt-3 block text-xs font-medium">Violation category<select value={category} onChange={(e) => setCategory(e.target.value as ViolationCategory)} className="mt-1 w-full rounded border p-2">{VIOLATION_CATEGORIES.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="mt-3 block text-xs font-medium">Explanation shown to student ({MIN_PUBLIC_REASON}–{MAX_REASON})<textarea value={publicReason} onChange={(e) => setPublicReason(e.target.value)} rows={4} className="mt-1 w-full rounded border p-2" /></label><label className="mt-3 block text-xs font-medium">Basis for action<select value={basis} onChange={(e) => setBasis(e.target.value as DeletionBasis)} className="mt-1 w-full rounded border p-2">{DELETION_BASES.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="mt-3 block text-xs font-medium">Optional supporting references (report, content or message IDs; no file upload required)<textarea value={evidence} onChange={(e) => setEvidence(e.target.value)} rows={2} className="mt-1 w-full rounded border p-2" /></label><label className="mt-2 flex gap-2 text-xs"><input checked={noEvidence} onChange={(e) => setNoEvidence(e.target.checked)} type="checkbox" />I understand that no supporting evidence is attached. I have documented the basis for this decision and confirm that scheduling permanent deletion is appropriate.</label></>}
  {mode === "immediate" && <label className="mt-3 flex gap-2 text-xs"><input checked={skipAppeal} onChange={(e) => setSkipAppeal(e.target.checked)} type="checkbox" />I acknowledge that the seven-day appeal period will be skipped.</label>}<label className="mt-3 block text-xs font-medium">Internal administrator note / cancellation reason ({MIN_INTERNAL_REASON}–{MAX_REASON}; never shown to student)<textarea value={internalReason} onChange={(e) => setInternalReason(e.target.value)} rows={3} className="mt-1 w-full rounded border p-2" /></label><label className="mt-3 block text-xs font-medium">Type {mode === "cancel" ? "CANCEL DELETION" : mode === "immediate" ? "DELETE NOW" : "DELETE"} to confirm<input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} className="mt-1 w-full rounded border p-2" /></label>{result && <p className={`mt-3 text-sm ${result.ok ? "text-emerald-700" : "text-red-700"}`}>{result.message}</p>}<div className="mt-5 flex gap-2"><button onClick={close} disabled={pending} className="flex-1 rounded border px-3 py-2 text-sm">Cancel</button><button onClick={() => void submit()} disabled={!valid || pending} className="flex-1 rounded bg-[#F02719] px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Submitting…" : mode === "cancel" ? "Cancel scheduled deletion" : mode === "immediate" ? "Delete immediately" : "Schedule deletion"}</button></div></div></div>}</div>;
}
